// src/dto/question-set.dto.ts

/**
 * Single interview question generated by AI
 * This is the atomic unit reused everywhere
 */
export type QuestionDTO = {
  question: string;
  options: string[];
  correctAnswers: number[]; // 0-based indexes
  explanation: string;
};

/**
 * Payload sent FROM client TO server
 * when generating questions
 */
export type GenerateQuestionsDTO = {
  jobDescription: string;
  saveQuestions?: boolean;
};

/**
 * Payload used INTERNALLY
 * after AI generation succeeds
 */
export type GeneratedQuestionSetDTO = {
  jobDescription: string;
  questions: QuestionDTO[];
};

/**
 * Payload sent FROM client TO server
 * when saving questions explicitly
 * (future-proof)
 */
export type SaveQuestionSetDTO = {
  jobDescription: string;
  questions: QuestionDTO[];
  isPublic?: boolean;
};

/**
 * Response sent TO client
 * after generation (and optional save)
 */
export type GenerateQuestionsResponseDTO = {
  questions: QuestionDTO[];
  saved?: boolean;
  questionSetId?: string;
};

/**
 * Public feed item (social-style)
 * Used for explore/search pages
 */
export type PublicQuestionSetDTO = {
  id: string;
  questionsPreview: QuestionDTO[]; // usually first 1–2
  authorName: string;
  createdAt: string;
};

/**
 * Full question set (owner view)
 */
export type QuestionSetDetailsDTO = {
  id: string;
  jobDescription: string;
  questions: QuestionDTO[];
  isPublic: boolean;
  createdAt: string;
  expiresAt: string | null;
};
