import { getPublicQuestionSets } from "@/lib/supabase/server";
import FeedCard from "@/components/feed/FeedCard";
import { Sparkles, TrendingUp } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function FeedPage() {
  const questions = await getPublicQuestionSets();

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-950 via-gray-900 to-black relative">
      <div className="fixed inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-emerald-900/20 via-transparent to-transparent pointer-events-none" />
      <div className="fixed inset-0 bg-grid-pattern opacity-10 pointer-events-none" />
      
      <main className="container max-w-7xl mx-auto px-4 md:px-6 py-24 relative z-10">
        {/* Header */}
        <div className="max-w-3xl mb-12">
          <div className="flex items-center gap-2 mb-3">
            <div className="p-2 rounded-lg bg-emerald-500/10 border border-emerald-500/20">
              <TrendingUp className="h-5 w-5 text-emerald-400" />
            </div>
            <span className="text-sm font-semibold text-emerald-400 uppercase tracking-wider">
              Community Feed
            </span>
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4 bg-gradient-to-r from-white to-gray-300 bg-clip-text text-transparent">
            Explore Interview Questions
          </h1>
          <p className="text-gray-400 text-lg leading-relaxed">
            Practice with real questions generated by other candidates. 
            Find your role and test your knowledge.
          </p>
        </div>

        {/* Content */}
        {questions.length === 0 ? (
          <div className="text-center py-24 border-2 border-dashed border-gray-700/50 rounded-2xl bg-gray-900/30 backdrop-blur-sm">
            <div className="w-16 h-16 mx-auto mb-6 rounded-full bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center">
              <Sparkles className="h-8 w-8 text-emerald-400" />
            </div>
            <h3 className="text-xl font-semibold text-white mb-2">No Public Questions Yet</h3>
            <p className="text-gray-400 max-w-md mx-auto">
              Be the first to share your interview questions with the community!
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
            {questions.map((q) => (
              <FeedCard key={q.id} data={q} />
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
