import { getPublicQuestionSets } from "@/lib/supabase/server";
import FeedCard from "@/components/feed/FeedCard";
import Header from "@/components/Header";
import { Sparkles } from "lucide-react";

export const dynamic = "force-dynamic";

export default async function FeedPage() {
  const questions = await getPublicQuestionSets();

  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <main className="container py-24">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-12">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <Sparkles className="h-5 w-5 text-purple-500" />
              <span className="text-sm font-semibold text-purple-500 uppercase tracking-wider">
                Community Feed
              </span>
            </div>
            <h1 className="text-3xl md:text-4xl font-bold text-foreground">
              Explore Recent Interviews
            </h1>
            <p className="mt-2 text-muted-foreground text-lg max-w-2xl">
              Practice with real questions generated by other candidates. 
              Find your role and test your knowledge.
            </p>
          </div>
        </div>

        {questions.length === 0 ? (
          <div className="text-center py-24 border border-dashed border-border rounded-xl">
            <p className="text-muted-foreground">No public questions yet. Be the first to share one!</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {questions.map((q) => (
              <FeedCard key={q.id} data={q} />
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
